set -g set-titles on
set -g set-titles-string "#h:#S"

set -g display-time 3000
set -g renumber-windows on

set -s buffer-limit 1      # Each copy operation creates a new buffer – we simply don't need it
set -g history-limit 10000

set -g mode-keys vi
set -g status-keys vi

if-shell 'test "$(uname)" = Darwin -a -x /opt/homebrew/bin/bash' {
    set -g default-shell /opt/homebrew/bin/bash
}
