# Set terminal tab title to host name
set -g set-titles on
set -g set-titles-string "#h"

set -g display-time 3000
set -g renumber-windows on

set -s buffer-limit 1      # Each copy operation creates a new buffer – we simply don't need it
set -g history-limit 10000

set -g mode-keys vi
set -g status-keys vi

# By default tmux sends terminal escape sequences which set terminal clipboard
# on text copying to buffer, but doesn't pass these terminal escape sequences
# from applications – so we use `set-clipboard on` to support reach terminal
# applications like OpenCode.
set -g set-clipboard on

# Clipboard support doesn't work when tmux is running under mosh which wraps it
# to its own pseudo terminal, so we have to workaround it -
# https://gist.github.com/yudai/95b20e3da66df1b066531997f982b57b
#
# It's also hard to determine whether we're running inside of mosh pseudo
# terminal. It doesn't set any environment variables, we don't even have mosh
# as a parent process and each tmux session creates a separate cgroups tree, so
# we have to guess here.
if-shell '[[ -n "$SSH_CONNECTION" && "$(uname)" = Linux ]] && pgrep --quiet --uid "$UID" --exact mosh-server' {
    set -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c%p1%.0s;%p2%s\\7"
}

if-shell '[[ "$(uname)" = Darwin && -x /opt/homebrew/bin/bash ]]' {
    set -g default-shell /opt/homebrew/bin/bash
}
