#!/bin/bash -e
#
# Updates all Vim plugins to the latest version
#

# Get path to the script directory -->
    script_path="${BASH_SOURCE[0]}"
    script_dir="$(dirname "$script_path")"

    while [ -h "$script_path" ]; do
        script_path="$(readlink "$script_path")"
        [[ $script_path != /* ]] && script_path="$script_dir/$script_path"
        script_dir="$(cd -P "$(dirname "$script_path")" && pwd)"
    done
    script_dir="$(cd -P "$(dirname "$script_path")" && pwd)"
# Get path to the script directory <--

# Go to the Vim directory
cd "$script_dir"

# Download spell files
mkdir -p spell
for lang in ru en; do
    for ext in spl sug; do
        echo;echo "Downloading $lang.$ext.."
        curl http://ftp.vim.org/vim/runtime/spell/$lang.utf-8.$ext -o spell/$lang.utf-8.$ext
    done
done

# Update all plugins
for plugin in pathogen bundle/*; do
    echo;echo "Updating $plugin..."
    ( cd "$plugin" && git checkout master && git pull && git submodule update )
done

# Recompile xkb-switch library
if [ "$(uname -o)" == "GNU/Linux" ]; then
    echo;echo "Compile xkb-switch..."
    (cd "bundle/xkb-switch" && cmake . && make && mv libxkbswitch.so "$script_dir/" && git clean -df)
fi
