#!/bin/sh -e
#
# Updates all Vim plugins to the latest version
#

# Get path to the script directory -->
    script_path="${BASH_SOURCE[0]}"
    script_dir="$(dirname "$script_path")"

    while [ -h "$script_path" ]; do
        script_path="$(readlink "$script_path")"
        [[ $script_path != /* ]] && script_path="$script_dir/$script_path"
        script_dir="$(cd -P "$(dirname "$script_path")" && pwd)"
    done
    script_dir="$(cd -P "$(dirname "$script_path")" && pwd)"
# Get path to the script directory <--

# Go to the Vim directory
cd "$script_dir"

# Download spell files
for lang in ru en; do
    for ext in spl sug; do
        wget -nv http://ftp.vim.org/vim/runtime/spell/$lang.utf-8.$ext -O spell/$lang.utf-8.$ext
    done
done

# Update all plugins
for plugin in pathogen bundle/*; do
    echo;echo "Updating $plugin..."
    ( cd "$plugin" && git pull )
done
