#!/bin/bash
#
# Vagrant user prep script
#

set -eu
sudo apt-get install -y git curl silversearcher-ag
sh <(curl https://raw.githubusercontent.com/KonishchevDmitry/dotfiles/master/bin/setup-dotfiles) --force
